### ISSUE TITLE
Front-end: update October Events

### ISSUE THREAD

**Issue by adriannaliu** [Code-4-Community/outstanding-life#77]
# Purpose
[October Events](https://github.com/Code-4-Community/outstanding-life/pull/71) was merged in because we were on a tight schedule, but there are still some PR comments that need to be addressed. David also sent back some edits, so that's included in this as well. 

# Description

**Questions to answer:**
* Are we able to get the header divider in the Programs page span the whole page (rather than just fit under "October 2022 Online Events")?
* [PR](https://github.com/Code-4-Community/outstanding-life/pull/71#discussion_r994843044): Why are we adding the whiteSpace="pre-line" attribute? This replaces white space with more than 2 spaces with a single space. Is our content just not formatted correctly?
* [PR](https://github.com/Code-4-Community/outstanding-life/pull/71#discussion_r994919979): Is this really the best way to store this information? At this point a line by line string is probably a bad representation.
* [PR](https://github.com/Code-4-Community/outstanding-life/pull/71#discussion_r994920208): Did you type this all in manually?

**Tasks**
- [ ] Monthly Writing Group: please replace the description with this:
> In this monthly writing workshop, we will discuss a short excerpt from fiction, non-fiction, or poetry. We will discuss its effectiveness either in form, style, point of view, or other literary devices/techniques. After considering what makes the passage work, we will use some aspect of the text as a prompt to jumpstart our own writing. The focus will be on short, in-class writing and discussion. Some experience in writing is required.

Referencing the screenshot below: 
- [ ] Please insert a new line between the two bios to make it more readable
- [ ] Would it be possible to either underline, italicize, or bold the "Bios of workshop leaders" line? Right now it kinda looks like it's just floating there
<img width="599" alt="Screen Shot 2022-10-19 at 9 40 45 PM" src="https://user-images.githubusercontent.com/72051204/196836158-dde5b9cf-eb8c-4868-8b53-8b46f16b5654.png">

- [ ] Following Izzy's [designs](https://www.figma.com/file/uKPcL5G1ZwVC3SGuacJco6/Outstanding-Life?node-id=1615%3A10586), implement a dropdown that allows you to switch between Upcoming Events and Past Events
<img width="661" alt="Screen Shot 2022-10-19 at 9 47 18 PM" src="https://user-images.githubusercontent.com/72051204/196836928-7af10266-5afc-451f-aa4a-98be270a0288.png">

# Acceptance Criteria
- [ ] Please attach before and after screenshots of the changes you've made to these pages.
